[phases.setup]
nixPkgs = ["go"]

[phases.build]
cmds = ["go mod download", "go build -o ebuse ./cmd/ebuse"]

[start]
cmd = "if [ -f /etc/ebuse/tenants.yaml ]; then ./ebuse -config /etc/ebuse/tenants.yaml; else ./ebuse; fi"
